name: Java CI with Maven

on:
  push:
    branches: [ branch-2.4.3-SNAPSHOT ]
  pull_request:
    branches: [ branch-2.4.3-SNAPSHOT ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
        ./build/mvn \
        -Dhadoop.version=2.9.1 \
        -Pyarn,hive,hive-thriftserver \
        -Pscala-2.11.7 \
        -Pkubernetes \
        -DskipTests \
        -q clean package --projects "!external/kafka-0-10,!>external/kafka-0-10-assembly,!external/kafka-0-10-sql"